apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails_kubernetes_test_deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rails_kubernetes_test
  template:
    metadata:
      labels:
        app: rails_kubernetes_test
    spec:
      containers:
        - name: rails_kubernetes_test
          image: ghcr.io/junkers21/rails_kubernetes_test:latest
          ports:
            - containerPort: 3000