apiVersion: v1
kind: Service
metadata:
  name: rails_kubernetes_test_load-balancer
spec:
  type: LoadBalancer
  selector:
    app: rails_kubernetes_test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http